// script.js

// 1. 단어 데이터 (여기에 원하는 단어를 50개 이상 채워넣으세요)
// '지성이 단어장' 데이터
const wordDatabaseJiseong = [
  { id: 451, word: "tough", meaning: "힘든, 곤란한" },
  { id: 452, word: "trade", meaning: "교환하다, 거래하다" },
  { id: 453, word: "traditional", meaning: "전통적인" },
  { id: 454, word: "trait", meaning: "특성" },
  { id: 455, word: "treatment", meaning: "대우, 취급, 치료" },
  { id: 456, word: "tribe", meaning: "부족" },
  { id: 457, word: "trick", meaning: "속이다" },
  { id: 458, word: "turn out to V", meaning: "~로 판명되다, 입증되다" },
  { id: 459, word: "typically", meaning: "일반적으로" },
  { id: 460, word: "useful", meaning: "유용한" },
  { id: 461, word: "via", meaning: "NN을 통해서, 경유하여" },
  { id: 462, word: "waste", meaning: "폐기물, 쓰레기, 낭비" },
  { id: 463, word: "weight", meaning: "무게" },
  { id: 464, word: "accurate", meaning: "정확한" },
  { id: 465, word: "adjust", meaning: "조정하다, 조절하다" },
  { id: 466, word: "afford to V", meaning: "~할 여유가 있다" },
  { id: 467, word: "aim", meaning: "목표, 목표로 하다" },
  { id: 468, word: "almost", meaning: "거의" },
  { id: 469, word: "alter", meaning: "바꾸다" },
  { id: 470, word: "anxious", meaning: "불안해하는, 염려하는" },
  { id: 471, word: "arrangement", meaning: "배열, 정렬" },
  { id: 472, word: "as long as SVO", meaning: "~하는 한" },
  { id: 473, word: "attach", meaning: "첨부하다, 붙이다" },
  { id: 474, word: "attention", meaning: "주의, 관심" },
  { id: 475, word: "attractive", meaning: "매력적인" },
  { id: 476, word: "billion", meaning: "10억" },
  { id: 477, word: "block", meaning: "막다" },
  { id: 478, word: "bond", meaning: "유대감, 친밀감" },
  { id: 479, word: "categorize", meaning: "분류하다" },
  { id: 480, word: "choir", meaning: "합창단" },
  { id: 481, word: "climate", meaning: "기후" },
  { id: 482, word: "cognitive", meaning: "인지의, 인식의" },
  { id: 483, word: "comment", meaning: "논평, 언급" },
  { id: 484, word: "be committed to Ving", meaning: "~에 헌신하다" },
  { id: 485, word: "compete", meaning: "경쟁하다" },
  { id: 486, word: "competitor", meaning: "경쟁자" },
  { id: 487, word: "composer", meaning: "작곡가" },
  { id: 488, word: "confuse", meaning: "혼란시키다" },
  { id: 489, word: "considerate", meaning: "사려 깊은" },
  { id: 490, word: "considerable", meaning: "상당한" },
  { id: 491, word: "consideration", meaning: "사려, 숙고" },
  { id: 492, word: "construct", meaning: "형성하다, 건축하다" },
  { id: 493, word: "contest", meaning: "대회" },
  { id: 494, word: "conversation", meaning: "대화" },
  { id: 495, word: "convey", meaning: "전달하다, 전하다" },
  { id: 496, word: "cultivate", meaning: "경작하다, 함양하다" },
  { id: 497, word: "declare", meaning: "선언하다" },
  { id: 498, word: "department", meaning: "학과, 부서" },
  { id: 499, word: "deserve", meaning: "~~을 받을만한 자격이 있다" },
  { id: 500, word: "difference", meaning: "차이점" },
  { id: 501, word: "director", meaning: "감독" },
  { id: 502, word: "disability", meaning: "장애" },
  { id: 503, word: "disappear", meaning: "사라지다" },
  { id: 504, word: "discovery", meaning: "발견" },
  { id: 505, word: "distinguish", meaning: "구별하다" },
  { id: 506, word: "divide", meaning: "나누다, 가르다" },
  { id: 507, word: "doubt", meaning: "의심하다" },
  { id: 508, word: "economic", meaning: "경제의" },
  { id: 509, word: "emerge", meaning: "등장하다" },
  { id: 510, word: "enthusiasm", meaning: "열정" },
  { id: 511, word: "even if SVO", meaning: "비록 ~일지라도" },
  { id: 512, word: "even though SVO", meaning: "비록 ~일지라도" },
  { id: 513, word: "evolution", meaning: "진화" },
  { id: 514, word: "exactly", meaning: "정확하게" },
  { id: 515, word: "examine", meaning: "검토하다" },
  { id: 516, word: "exceed", meaning: "초과하다" },
  { id: 517, word: "existence", meaning: "존재" },
  { id: 518, word: "expect", meaning: "기대하다, 요구하다, 예상하다" },
  { id: 519, word: "extreme", meaning: "극단적인" },
  { id: 520, word: "facility", meaning: "시설" },
  { id: 521, word: "fellow", meaning: "동료" },
  { id: 522, word: "female", meaning: "여성의" },
  { id: 523, word: "field", meaning: "분야, 영역, 현장" },
  { id: 524, word: "frequency", meaning: "빈번함, 빈도" },
  { id: 525, word: "gene", meaning: "유전자" },
  { id: 526, word: "gentle", meaning: "부드러운" },
  { id: 527, word: "genuine", meaning: "진짜의" },
  { id: 528, word: "host", meaning: "주최하다" },
  { id: 529, word: "improvement", meaning: "개선" },
  { id: 530, word: "increase", meaning: "증가하다" },
  { id: 531, word: "incredible", meaning: "믿을 수 없는" },
  { id: 532, word: "infant", meaning: "유아" },
  { id: 533, word: "innovation", meaning: "혁신" },
  { id: 534, word: "insight", meaning: "통찰력" },
  { id: 535, word: "instantly", meaning: "즉시" },
  { id: 536, word: "instrument", meaning: "도구, 기구" },
  { id: 537, word: "intelligence", meaning: "지능" },
  { id: 538, word: "interrupt", meaning: "방해하다, 중단하다" },
  { id: 539, word: "introduce", meaning: "도입하다, 소개하다" },
  { id: 540, word: "investigate", meaning: "조사하다" },
  { id: 541, word: "isolation", meaning: "고립" },
  { id: 542, word: "issue", meaning: "이슈, 주제, 발급하다" },
  { id: 543, word: "knowledge", meaning: "지식" },
  { id: 544, word: "launch", meaning: "시작하다, 개시하다, 발사하다" },
  { id: 545, word: "lay", meaning: "놓다, 두다" },
  { id: 546, word: "length", meaning: "길이" },
  { id: 547, word: "local", meaning: "지역의, 지방의, 부분적인" },
  { id: 548, word: "look for", meaning: "찾다" },
  { id: 549, word: "loss", meaning: "상실" },
  { id: 550, word: "manner", meaning: "방식, 태도" },
  { id: 551, word: "means", meaning: "수단, 방법" },
  { id: 552, word: "method", meaning: "방법" },
  { id: 553, word: "minor", meaning: "사소한, 작은" },
  { id: 554, word: "mistaken", meaning: "잘못된" },
  { id: 555, word: "nature", meaning: "성격, 본성, 자연" },
  { id: 556, word: "nod", meaning: "끄덕이다, 동의하다" },
  { id: 557, word: "occasion", meaning: "경우" },
  { id: 558, word: "on behalf of", meaning: "NN을 대표해서, 대신해서" },
  { id: 559, word: "order", meaning: "순서, 규칙, 주문하다" },
  { id: 560, word: "ordinary", meaning: "평범한, 일반적인" },
  { id: 561, word: "participation", meaning: "참가, 참여" },
  { id: 562, word: "patient", meaning: "환자, 인내심 있는" },
  { id: 563, word: "persuade", meaning: "설득하다" },
  { id: 564, word: "phrase", meaning: "구절" },
  { id: 565, word: "physics", meaning: "물리학" },
  { id: 566, word: "poison", meaning: "독" },
  { id: 567, word: "precious", meaning: "귀중한" },
  { id: 568, word: "prevent", meaning: "막다" },
  { id: 569, word: "produce", meaning: "생산하다" },
  { id: 570, word: "psychology", meaning: "심리학" },
  { id: 571, word: "quite", meaning: "상당히, 꽤" },
  { id: 572, word: "recall", meaning: "회상하다" },
  { id: 573, word: "recognition", meaning: "인지" },
  { id: 574, word: "regret", meaning: "유감, 후회" },
  { id: 575, word: "regular", meaning: "상시의, 정기적인" },
  { id: 576, word: "regulation", meaning: "조절, 규제" },
  { id: 577, word: "relatively", meaning: "비교적으로, 상대적으로" },
  { id: 578, word: "reliable", meaning: "믿을 수 있는" },
  { id: 579, word: "reputation", meaning: "평판, 명성" },
  { id: 580, word: "reserve", meaning: "예약하다" },
    { id: 581, word: "resolve", meaning: "해결하다" },
  { id: 582, word: "resource", meaning: "자원" },
  { id: 583, word: "satisfy", meaning: "만족시키다" },
  { id: 584, word: "saying", meaning: "속담, 격언" },
  { id: 585, word: "seek", meaning: "추구하다, 찾다" },
  { id: 586, word: "similar", meaning: "유사한" },
  { id: 587, word: "social", meaning: "사회적인" },
  { id: 588, word: "solid", meaning: "단단한, 고체의, 단색의" },
  { id: 589, word: "starve", meaning: "굶주리다" },
  { id: 590, word: "status", meaning: "지위" },
  { id: 591, word: "still", meaning: "여전히, 조용한, 하지만" },
  { id: 592, word: "stimulate", meaning: "자극하다" },
  { id: 593, word: "stimuli", meaning: "자극" },
  { id: 594, word: "suspect", meaning: "의심하다" },
  { id: 595, word: "tackle", meaning: "다루다" },
  { id: 596, word: "term", meaning: "용어, 기간, 조건" },
  { id: 597, word: "that is", meaning: "즉" },
  { id: 598, word: "theory", meaning: "이론, 학설, 견해" },
  { id: 599, word: "therefore", meaning: "따라서, 그러므로" },
  { id: 600, word: "translate", meaning: "번역하다" },
  { id: 601, word: "typical", meaning: "전형적인" },
  { id: 602, word: "undesirable", meaning: "바람직하지 않은" },
  { id: 603, word: "unfamiliar", meaning: "익숙하지 않은, 친숙하지 않은" },
  { id: 604, word: "up to N", meaning: "(최대) N까지" },
  { id: 605, word: "urban", meaning: "도시의" },
  { id: 606, word: "urge", meaning: "충동, 욕구, 촉구하다" },
  { id: 607, word: "various", meaning: "다양한" },
  { id: 608, word: "vary", meaning: "다르다" },
  { id: 609, word: "virtually", meaning: "사실상, 거의" },
  { id: 610, word: "visible", meaning: "보이는" },
  { id: 611, word: "vital", meaning: "필수적인" },
  { id: 612, word: "volunteer", meaning: "자원봉사하다" },
  { id: 613, word: "abuse", meaning: "남용, 학대, 오용하다" },
  { id: 614, word: "academic", meaning: "학업의" },
  { id: 615, word: "achievement", meaning: "성취" },
  { id: 616, word: "activate", meaning: "활성화시키다" },
  { id: 617, word: "admire", meaning: "칭찬하다, 감탄하다" },
  { id: 618, word: "admit", meaning: "인정하다, 허락하다" },
  { id: 619, word: "adopt", meaning: "채택하다, 입양하다" },
  { id: 620, word: "alert", meaning: "기민한, 각성한" },
  { id: 621, word: "annual", meaning: "매년의, 연례의" },
  { id: 622, word: "appealing", meaning: "매력적인, 흥미로운" },
  { id: 623, word: "assistant", meaning: "조수, 보조원" },
  { id: 624, word: "athletic", meaning: "운동의, 체육의" },
  { id: 625, word: "attentive", meaning: "주의 깊은, 배려하는" },
  { id: 626, word: "awareness", meaning: "인식" },
  { id: 627, word: "back and forth", meaning: "앞뒤로" },
  { id: 628, word: "involved in N", meaning: "~에 참여하는, 관련된" },
  { id: 629, word: "be used to V", meaning: "~하기 위해 사용되다" },
  { id: 630, word: "be used to Ving", meaning: "~하는 데 익숙하다" },
  { id: 631, word: "used to V", meaning: "~하곤 했다" },
  { id: 632, word: "beat", meaning: "(심장 등이) 뛰다" },
  { id: 633, word: "behave", meaning: "행동하다" },
  { id: 634, word: "below N", meaning: "N의 아래에" },
  { id: 635, word: "besides", meaning: "게다가, 또한" },
  { id: 636, word: "beyond N", meaning: "N을 넘어서" },
  { id: 637, word: "bias", meaning: "편견" },
  { id: 638, word: "bill", meaning: "청구서, 지폐" },
  { id: 639, word: "bite", meaning: "한 입" },
  { id: 640, word: "blame", meaning: "비난하다, 비난" },
  { id: 641, word: "blanket", meaning: "담요" },
  { id: 642, word: "bless", meaning: "축복하다" },
  { id: 643, word: "burden", meaning: "부담, 짐" },
  { id: 644, word: "bury", meaning: "묻다, 매장하다" },
  { id: 645, word: "career", meaning: "직업, 경력" },
  { id: 646, word: "category", meaning: "범주" },
  { id: 647, word: "certificate", meaning: "수료증" },
  { id: 648, word: "chemical", meaning: "화학물질" },
  { id: 649, word: "clue", meaning: "단서" },
  { id: 650, word: "compassion", meaning: "연민" },
  { id: 651, word: "competence", meaning: "능력, 역량" },
  { id: 652, word: "complaint", meaning: "불평" },
  { id: 653, word: "complicated", meaning: "복잡한" },
  { id: 654, word: "confront", meaning: "직면하다" },
  { id: 655, word: "construction", meaning: "건축물" },
  { id: 656, word: "convenient", meaning: "편리한" },
  { id: 657, word: "cope with N", meaning: "N에 대처하다" },
  { id: 658, word: "correct", meaning: "옳은, 수정하다" },
  { id: 659, word: "count", meaning: "세다, 중요하다" },
  { id: 660, word: "cover", meaning: "다루다, 덮다" },
  { id: 661, word: "currently", meaning: "현재" },
  { id: 662, word: "decide", meaning: "결정하다" },
  { id: 663, word: "definition", meaning: "정의" },
  { id: 664, word: "degree", meaning: "정도, 학위" },
  { id: 665, word: "delight", meaning: "기쁨, 기쁘게 하다" },
  { id: 666, word: "delighted", meaning: "기쁜" },
  { id: 667, word: "deny", meaning: "부인하다" },
  { id: 668, word: "destroy", meaning: "파괴하다" },
  { id: 669, word: "directly", meaning: "직접적으로" },
  { id: 670, word: "discount", meaning: "할인" },
  { id: 671, word: "discourage", meaning: "낙담시키다" },
  { id: 672, word: "disrupt", meaning: "방해하다" },
  { id: 673, word: "distance", meaning: "거리" },
  { id: 674, word: "distant", meaning: "먼" },
  { id: 675, word: "distress", meaning: "곤경" },
  { id: 676, word: "disturb", meaning: "방해하다" },
  { id: 677, word: "donation", meaning: "기부" },
  { id: 678, word: "ecosystem", meaning: "생태계" },
  { id: 679, word: "encounter", meaning: "맞닥뜨리다" },
  { id: 680, word: "entirely", meaning: "완전히" },
  { id: 681, word: "equally", meaning: "동등하게" },
  { id: 682, word: "evaluate", meaning: "평가하다" },
  { id: 683, word: "exhausted", meaning: "지친" },
  { id: 684, word: "explanation", meaning: "설명" },
  { id: 685, word: "extremely", meaning: "극도로" },
  { id: 686, word: "face", meaning: "직면하다" },
  { id: 687, word: "favor", meaning: "부탁" },
  { id: 688, word: "fear", meaning: "두려움" },
  { id: 689, word: "flexible", meaning: "유연한" },
  { id: 690, word: "follow", meaning: "따라가다" },
  { id: 691, word: "foreign", meaning: "외국의" },
  { id: 692, word: "found", meaning: "설립하다" },
  { id: 693, word: "free will", meaning: "자유 의지" },
  { id: 694, word: "frustration", meaning: "좌절" },
  { id: 695, word: "gather", meaning: "모이다, 모으다" },
  { id: 696, word: "generous", meaning: "관대한" },
  { id: 697, word: "get along with N", meaning: "N와 잘 지내다" },
  { id: 698, word: "government", meaning: "정부" },
  { id: 699, word: "gradually", meaning: "점차적으로" },
  { id: 700, word: "growth", meaning: "성장" },
  { id: 701, word: "hardly", meaning: "거의 ~않다" },
  { id: 702, word: "hire", meaning: "고용하다" },
  { id: 703, word: "household", meaning: "가정" },
  { id: 704, word: "huge", meaning: "거대한" },
  { id: 705, word: "humanity", meaning: "인류, 인간성" },
  { id: 706, word: "illustrate", meaning: "분명히 보여주다" },
  { id: 707, word: "in essence", meaning: "본질적으로" },
  { id: 708, word: "in return", meaning: "대가로" },
  { id: 709, word: "inadequate", meaning: "부적당한, 부족한" },
  { id: 710, word: "incredibly", meaning: "놀랍게도" },
  { id: 711, word: "indication", meaning: "표시, 암시" },
  { id: 712, word: "industrial", meaning: "산업의" },
  { id: 713, word: "innovative", meaning: "혁신적인" },
  { id: 714, word: "insist", meaning: "주장하다" },
  { id: 715, word: "instance", meaning: "예시" },
  { id: 716, word: "intellectual", meaning: "지적인" },
  { id: 717, word: "intend", meaning: "의도하다" },
  { id: 718, word: "interfere (with N)", meaning: "(N을) 방해하다" },
  { id: 719, word: "invisible", meaning: "보이지 않는" },
  { id: 720, word: "label", meaning: "꼬리표, 음반회사" },
  { id: 721, word: "limit", meaning: "제한하다" },
  { id: 722, word: "link", meaning: "연결하다" },
  { id: 723, word: "locate", meaning: "위치를 찾다" },
  { id: 724, word: "mammal", meaning: "포유류" },
  { id: 725, word: "management", meaning: "관리" },
  { id: 726, word: "manufacturer", meaning: "제조업자, 제조회사" },
  { id: 727, word: "mature", meaning: "어른스러운, 성숙한" },
  { id: 728, word: "mean", meaning: "1. 의미하다 2. 사악한" },
  { id: 729, word: "meaningful", meaning: "의미 있는, 중요한" },
  { id: 730, word: "meet", meaning: "1. 충족시키다 2. 만나다" },
  { id: 731, word: "mental", meaning: "마음의, 정신의" },
  { id: 732, word: "mention", meaning: "언급하다" },
  { id: 733, word: "minimal", meaning: "최소의" },
  { id: 734, word: "minimum", meaning: "최소" },
  { id: 735, word: "moisture", meaning: "습기" },
  { id: 736, word: "moment", meaning: "순간" },
  { id: 737, word: "monitor", meaning: "감시하다, 모니터하다" },
  { id: 738, word: "moral", meaning: "도덕의" },
  { id: 739, word: "moreover", meaning: "게다가" },
  { id: 740, word: "mostly", meaning: "대부분" },
  { id: 741, word: "mutual", meaning: "상호적인" },
  { id: 742, word: "native", meaning: "원산지의, 원주의" },
  { id: 743, word: "natural", meaning: "자연의, 천연의" },
  { id: 744, word: "necessary", meaning: "필요한, 필수적인" },
  { id: 745, word: "neighborhood", meaning: "동네, 근처, 이웃" },
  { id: 746, word: "nevertheless", meaning: "그럼에도 불구하고" },
  { id: 747, word: "nonverbal", meaning: "비언어적인" },
  { id: 748, word: "normal", meaning: "정상적인" },
  { id: 749, word: "nutrient", meaning: "영양소, 영양" },
  { id: 750, word: "observer", meaning: "관찰자" },
  { id: 751, word: "occasional", meaning: "때때로의" },
  { id: 752, word: "on average", meaning: "평균적으로" },
  { id: 753, word: "option", meaning: "선택" },
  { id: 754, word: "output", meaning: "생산량, 결과물" },
  { id: 755, word: "overestimate", meaning: "과대평가하다" },
  { id: 756, word: "ownership", meaning: "소유" },
  { id: 757, word: "pace", meaning: "속도, 페이스" },
  { id: 758, word: "partly", meaning: "부분적으로" },
  { id: 759, word: "pass on", meaning: "물려주다" },
  { id: 760, word: "philosopher", meaning: "철학자" },
  { id: 761, word: "pioneer", meaning: "개척자" },
  { id: 762, word: "plant", meaning: "1. 식물 2. 공장" },
  { id: 763, word: "plate", meaning: "접시, 1인분(의 요리)" },
  { id: 764, word: "play a role", meaning: "역할을 하다" },
  { id: 765, word: "please", meaning: "기쁘게 하다" },
  { id: 766, word: "pleasure", meaning: "즐거움" },
  { id: 767, word: "polite", meaning: "예의바른, 공손한" },
  { id: 768, word: "popularity", meaning: "인기" },
  { id: 769, word: "pose", meaning: "(질문을) 제기하다" },
  { id: 770, word: "precisely", meaning: "정확하게" },
  { id: 771, word: "predict", meaning: "예측하다" },
  { id: 772, word: "prefer", meaning: "선호하다" },
  { id: 773, word: "presence", meaning: "존재" },
  { id: 774, word: "presentation", meaning: "제시, 발표" },
  { id: 775, word: "prevention", meaning: "예방, 방지" },
  { id: 776, word: "principal", meaning: "교장" },
  { id: 777, word: "productive", meaning: "생산성 있는" },
  { id: 778, word: "proper", meaning: "적절한" },
  { id: 779, word: "punish", meaning: "벌주다" },
  { id: 780, word: "recommendation", meaning: "추천" },
  { id: 781, word: "refund", meaning: "환불" },
  { id: 782, word: "refuse", meaning: "거절하다, 거부하다" },
  { id: 783, word: "reject", meaning: "거절하다" },
  { id: 784, word: "religious", meaning: "종교의" },
  { id: 785, word: "remarkably", meaning: "주목할 만하게, 현저하게" },
  { id: 786, word: "remote", meaning: "멀리 떨어진, 원격의" },
  { id: 787, word: "resistance", meaning: "저항" },
  { id: 788, word: "restrict", meaning: "제한하다" },
  { id: 789, word: "risky", meaning: "위험한" },
  { id: 790, word: "senior", meaning: "노인" },
  { id: 791, word: "session", meaning: "회차, 세션" },
  { id: 792, word: "shape", meaning: "모양, 형태를 잡다" },
  { id: 793, word: "shorten", meaning: "줄이다" },
  { id: 794, word: "sight", meaning: "시력" },
  { id: 795, word: "sink", meaning: "가라앉다, 싱크대" },
  { id: 796, word: "sort", meaning: "분류하다, 종류" },
  { id: 797, word: "souvenir", meaning: "기념품" },
  { id: 798, word: "spoil", meaning: "상하다, 망치다" },
  { id: 799, word: "store", meaning: "1. 상점 2. 저장하다" },
  { id: 800, word: "stranger", meaning: "낯선 사람" },
  { id: 801, word: "stuff", meaning: "물건, 꽉 채우다" },
  { id: 802, word: "take advantage of", meaning: "이용하다" },
  { id: 803, word: "take off", meaning: "이륙하다" },
  { id: 804, word: "talent", meaning: "재능" },
  { id: 805, word: "unfavorable", meaning: "불리한" },
  { id: 806, word: "unpleasant", meaning: "불쾌한" },
  { id: 807, word: "upcoming", meaning: "다가오는" },
  { id: 808, word: "utilize", meaning: "활용하다, 이용하다" },
  { id: 809, word: "valuable", meaning: "가치있는" },
  { id: 810, word: "violate", meaning: "위반하다" },
  { id: 811, word: "widespread", meaning: "광범위한" },
  { id: 812, word: "wildlife", meaning: "야생" },
  { id: 813, word: "within N", meaning: "N내로, 이내로" },
  { id: 814, word: "a great deal of", meaning: "다량의, 많은" },
  { id: 815, word: "a variety of Ns", meaning: "다양한 N들" },
  { id: 816, word: "abandon", meaning: "버리다" },
  { id: 817, word: "above N", meaning: "N 위에" },
  { id: 818, word: "abstract", meaning: "추상적인" },
  { id: 819, word: "acceptable", meaning: "받아들여질 수 있는" },
  { id: 820, word: "accessible", meaning: "접근하기 쉬운" },
  { id: 821, word: "accordingly", meaning: "따라서" },
  { id: 822, word: "account", meaning: "1. 설명 2. 계좌" },
  { id: 823, word: "account for N", meaning: "차지하다, 설명하다" },
  { id: 824, word: "active", meaning: "적극적인" },
  { id: 825, word: "adequate", meaning: "적절한" },
  { id: 826, word: "adequately", meaning: "적절하게" },
  { id: 827, word: "aid", meaning: "1. 돕다 2. 도움" },
  { id: 828, word: "along N", meaning: "N을 따라서" },
  { id: 829, word: "along with N", meaning: "N과 함께" },
  { id: 830, word: "alternative", meaning: "대안적인, 대안" },
  { id: 831, word: "although", meaning: "비록 ~일지라도" },
  { id: 832, word: "analysis", meaning: "분석" },
  { id: 833, word: "ancient", meaning: "고대의" },
  { id: 834, word: "anthropologist", meaning: "인류학자" },
  { id: 835, word: "apology", meaning: "사과" },
  { id: 836, word: "as well", meaning: "또한" },
  { id: 837, word: "assist", meaning: "돕다" },
  { id: 838, word: "assistance", meaning: "도움, 지원" },
  { id: 839, word: "at once", meaning: "동시에" },
  { id: 840, word: "athlete", meaning: "운동선수" },
  { id: 841, word: "atom", meaning: "원자" },
  { id: 842, word: "attraction", meaning: "관심을 끄는 것" },
  { id: 843, word: "awkward", meaning: "어색한" },
  { id: 844, word: "barely", meaning: "거의 ~않다" },
  { id: 845, word: "bark", meaning: "짖다, 나무껍데기" },
  { id: 846, word: "barrier", meaning: "장벽" },
  { id: 847, word: "basis", meaning: "기초, 기반" },
  { id: 848, word: "good at N", meaning: "~를 잘하는" },
  { id: 849, word: "known as N", meaning: "N로 알려진" },
  { id: 850, word: "known for N", meaning: "N 때문에 알려진" },
  { id: 851, word: "proud of N", meaning: "자랑스러워하는" },
  { id: 852, word: "willing to V", meaning: "기꺼이 ~하는" },
  { id: 853, word: "bend", meaning: "구부러지다" },
  { id: 854, word: "beverage", meaning: "음료" },
  { id: 855, word: "biologist", meaning: "생물학자" },
  { id: 856, word: "blind", meaning: "눈 먼" },
  { id: 857, word: "board", meaning: "탑승하다, 이사회" },
  { id: 858, word: "boost", meaning: "증대시키다" },
  { id: 859, word: "boundary", meaning: "경계" },
  { id: 860, word: "briefly", meaning: "잠시, 간단히" },
  { id: 861, word: "budget", meaning: "예산" },
  { id: 862, word: "by N", meaning: "N만큼, ~에 의해" },
  { id: 863, word: "candidate", meaning: "후보자" },
  { id: 864, word: "capture", meaning: "포획하다" },
  { id: 865, word: "caution", meaning: "주의" },
  { id: 866, word: "cell", meaning: "세포" },
  { id: 867, word: "character", meaning: "등장인물, 성격" },
  { id: 868, word: "charity", meaning: "자선 단체" },
  { id: 869, word: "childhood", meaning: "어린 시절" },
  { id: 870, word: "choice", meaning: "선택" },
  { id: 871, word: "civilization", meaning: "문명" },
  { id: 872, word: "client", meaning: "의뢰인" },
  { id: 873, word: "climb", meaning: "오르다" },
  { id: 874, word: "command", meaning: "명령" },
  { id: 875, word: "commercial", meaning: "상업적인" },
  { id: 876, word: "commonly", meaning: "보통" },
  { id: 877, word: "compel", meaning: "강요하다" },
  { id: 878, word: "complain", meaning: "불평하다" },
  { id: 879, word: "component", meaning: "구성요소" },
  { id: 880, word: "conceal", meaning: "감추다" },
  { id: 881, word: "confirm", meaning: "확인하다" },
  { id: 882, word: "consciously", meaning: "의식적으로" },
  { id: 883, word: "consist of", meaning: "구성되다" },
  { id: 884, word: "consistent", meaning: "일관된" },
  { id: 885, word: "consult", meaning: "상담하다" },
  { id: 886, word: "content", meaning: "만족한, 내용물" },
  { id: 887, word: "continue", meaning: "계속하다" },
  { id: 888, word: "contrast", meaning: "대조하다" },
  { id: 889, word: "control", meaning: "통제하다" },
  { id: 890, word: "convenience", meaning: "편리함" },
  { id: 891, word: "countless", meaning: "무수한" },
  { id: 892, word: "courage", meaning: "용기" },
  { id: 893, word: "craft", meaning: "공예" },
  { id: 894, word: "creative", meaning: "창조적인" },
  { id: 895, word: "crew", meaning: "단원" },
  { id: 896, word: "crime", meaning: "범죄" },
  { id: 897, word: "criticism", meaning: "비판" },
  { id: 898, word: "curious", meaning: "호기심 있는" },
  { id: 899, word: "deal", meaning: "거래" },
  { id: 900, word: "debt", meaning: "빚" },
  { id: 901, word: "defense", meaning: "방어" },
  { id: 902, word: "deliver", meaning: "전달하다" },
  { id: 903, word: "dependent", meaning: "의존적인" },
  { id: 904, word: "depression", meaning: "우울" },
  { id: 905, word: "design", meaning: "설계하다" },
  { id: 906, word: "destination", meaning: "목적지" },
  { id: 907, word: "differ", meaning: "다르다" },
  { id: 908, word: "disaster", meaning: "재난" },
  { id: 909, word: "discomfort", meaning: "불편함" },
  { id: 910, word: "distract", meaning: "집중을 방해하다" },
  { id: 911, word: "document", meaning: "문서" },
  { id: 912, word: "doubtful", meaning: "의심스러운" },
  { id: 913, word: "drought", meaning: "가뭄" },
  { id: 914, word: "during N", meaning: "N 동안" },
  { id: 915, word: "duty", meaning: "의무" },
  { id: 916, word: "each other", meaning: "서로" },
  { id: 917, word: "editor", meaning: "편집자" },
  { id: 918, word: "educate", meaning: "교육하다" },
  { id: 919, word: "element", meaning: "요소" },
  { id: 920, word: "emission", meaning: "배출" },
  { id: 921, word: "emotional", meaning: "감정적인" },
  { id: 922, word: "employ", meaning: "고용하다" },
  { id: 923, word: "empty", meaning: "비어 있는" },
  { id: 924, word: "end up Ving", meaning: "결국 ~하게 되다" },
  { id: 925, word: "engage", meaning: "사로잡다" },
  { id: 926, word: "enormous", meaning: "막대한" },
  { id: 927, word: "enrich", meaning: "풍요롭게 하다" },
  { id: 928, word: "enroll", meaning: "등록하다" },
  { id: 929, word: "entrance", meaning: "입구" },
  { id: 930, word: "equal", meaning: "동등한" },
  { id: 931, word: "essentially", meaning: "근본적으로" },
  { id: 932, word: "ethical", meaning: "윤리적인" },
  { id: 933, word: "evident", meaning: "명백한" },
  { id: 934, word: "exact", meaning: "정확한" },
  { id: 935, word: "exhibition", meaning: "전시회" },
  { id: 936, word: "existing", meaning: "기존의" },
  { id: 937, word: "exotic", meaning: "이국적인" },
  { id: 938, word: "expertise", meaning: "전문지식" },
  { id: 939, word: "extensive", meaning: "광범위한" },
  { id: 940, word: "fascinating", meaning: "매력적인" },
  { id: 941, word: "fashion", meaning: "유행, 패션" },
  { id: 942, word: "feel like Ving", meaning: "~하고 싶다" },
  { id: 943, word: "financial", meaning: "재정적인" },
  { id: 944, word: "fine", meaning: "좋은, 벌금" },
  { id: 945, word: "flight", meaning: "비행" },
  { id: 946, word: "float", meaning: "뜨다" },
  { id: 947, word: "flood", meaning: "범람시키다" },
  { id: 948, word: "forest", meaning: "숲" },
  { id: 949, word: "forgive", meaning: "용서하다" },
  { id: 950, word: "former", meaning: "이전의" },
  { id: 951, word: "foundation", meaning: "기초, 재단" },
  { id: 952, word: "free", meaning: "무료의, 자유로운" },
  { id: 953, word: "frequent", meaning: "빈번한" },
  { id: 954, word: "friction", meaning: "마찰" },
  { id: 955, word: "fuel", meaning: "연료" },
  { id: 956, word: "funeral", meaning: "장례식" },
  { id: 957, word: "fur", meaning: "모피" },
  { id: 958, word: "general", meaning: "일반적인" },
  { id: 959, word: "grain", meaning: "곡식" },
  { id: 960, word: "grant", meaning: "수여하다, 보조금" },
  { id: 961, word: "gratitude", meaning: "감사" },
  { id: 962, word: "guilt", meaning: "죄책감" },
  { id: 963, word: "habitat", meaning: "서식지" },
  { id: 964, word: "hardship", meaning: "고난" },
  { id: 965, word: "harmful", meaning: "해로운" },
  { id: 966, word: "harsh", meaning: "가혹한" },
  { id: 967, word: "harvest", meaning: "수확하다" },
  { id: 968, word: "hence", meaning: "따라서" },
  { id: 969, word: "hesitate", meaning: "망설이다" },
  { id: 970, word: "hollow", meaning: "텅 빈" },
  { id: 971, word: "honesty", meaning: "정직" },
  { id: 972, word: "hunter-gatherer", meaning: "수렵 채집인" },
  { id: 973, word: "identification", meaning: "신분확인, 신원증명" },
  { id: 974, word: "imagination", meaning: "상상력" },
  { id: 975, word: "impossible", meaning: "불가능한" },
{ id: 976, word: "impressive", meaning: "인상 깊은, 인상적인" },
{ id: 977, word: "in other words", meaning: "다른 말로" },
{ id: 978, word: "in the short run", meaning: "단기적으로" },
{ id: 979, word: "income", meaning: "수입, 소득" },
{ id: 980, word: "inconvenience", meaning: "불편함" },
{ id: 981, word: "increasingly", meaning: "점차적으로" },
{ id: 982, word: "independent", meaning: "독립된, 독립적인" },
{ id: 983, word: "indicator", meaning: "지표" },
  { id: 984, word: "individually", meaning: "개별적으로, 개인적으로" },
{ id: 985, word: "injury", meaning: "상처, 부상" },
{ id: 986, word: "inspiration", meaning: "영감" },
{ id: 987, word: "install", meaning: "설치하다, 설비하다" },
{ id: 988, word: "instinct", meaning: "본능" },
{ id: 989, word: "instruct", meaning: "교육하다, 가르치다" },
{ id: 990, word: "instructor", meaning: "교사" },
{ id: 991, word: "intake", meaning: "섭취" },
{ id: 992, word: "intense", meaning: "강한" },
{ id: 993, word: "intensity", meaning: "강함, 강도" },
{ id: 994, word: "interference", meaning: "간섭, 개입, 방해" },
{ id: 995, word: "international", meaning: "국제적인" },
{ id: 996, word: "interval", meaning: "간격" },
{ id: 997, word: "invent", meaning: "발명하다" },
{ id: 998, word: "invest", meaning: "투자하다" },
{ id: 999, word: "investment", meaning: "투자" },
{ id: 1000, word: "journey", meaning: "여정, 여행" },
{ id: 1001, word: "last", meaning: "1. 마지막의, 마지막 2. 지속되다" },
{ id: 1002, word: "latest", meaning: "최신의" },
{ id: 1003, word: "least", meaning: "최소의" },
{ id: 1004, word: "license", meaning: "허가하다" },
{ id: 1005, word: "lift", meaning: "들어 올리다" },
{ id: 1006, word: "likelihood", meaning: "가능성" },
{ id: 1007, word: "likely", meaning: "1. (부) 아마도 2. (형) 가능성 있는" },
{ id: 1008, word: "literally", meaning: "말 그대로" },
{ id: 1009, word: "literature", meaning: "문학" },
{ id: 1010, word: "lonely", meaning: "외로운" },
{ id: 1011, word: "long-term", meaning: "장기적인" },
{ id: 1012, word: "loyal", meaning: "충성심이 있는" },
{ id: 1013, word: "loyalty", meaning: "충실, 충성, 충성심" },
{ id: 1014, word: "lung", meaning: "폐" },
{ id: 1015, word: "maintenance", meaning: "유지, 유지보수" },
{ id: 1016, word: "manage", meaning: "관리하다, 다루다" },
{ id: 1017, word: "marine", meaning: "바다의, 해양의" },
{ id: 1018, word: "massive", meaning: "거대한" },
{ id: 1019, word: "match", meaning: "시합, 성냥" },
{ id: 1020, word: "mate", meaning: "짝, 번식하다" },
{ id: 1021, word: "maximum", meaning: "최대의" },
{ id: 1022, word: "mechanism", meaning: "매커니즘, 과정, 체계" },
{ id: 1023, word: "medical", meaning: "의학의, 의료의" },
{ id: 1024, word: "merchant", meaning: "상인" },
{ id: 1025, word: "mess", meaning: "엉망인 상태, 엉망진창, 더러움" },
{ id: 1026, word: "misfortune", meaning: "불행" },
{ id: 1027, word: "mislead", meaning: "오해하게 하다, 잘못되게 이끌다" },
{ id: 1028, word: "multiple", meaning: "다수의" },
{ id: 1029, word: "mysterious", meaning: "신비로운" },
{ id: 1030, word: "myth", meaning: "신화" },
{ id: 1031, word: "narrow", meaning: "좁은, 좁히다" },
{ id: 1032, word: "necessity", meaning: "필수품" },
{ id: 1033, word: "need", meaning: "1. 도움, 필요, 필요로 하다 2. 욕구" },
{ id: 1034, word: "negotiate", meaning: "협상하다" },
{ id: 1035, word: "negotiation", meaning: "협상" },
{ id: 1036, word: "newborn", meaning: "신생아" },
{ id: 1037, word: "no matter how", meaning: "아무리 ~할지라도" },
{ id: 1038, word: "norm", meaning: "규범" },
{ id: 1039, word: "normally", meaning: "일반적으로" },
{ id: 1040, word: "nutrition", meaning: "영양소, 영양" },
{ id: 1041, word: "obviously", meaning: "분명히, 확실히, 명백히" },
{ id: 1042, word: "odd", meaning: "1. 이상한 2. 가능성, 확률 3. 홀수의" },
{ id: 1043, word: "official", meaning: "공무원, 공식적인" },
{ id: 1044, word: "opponent", meaning: "적수" },
{ id: 1045, word: "organ", meaning: "(신체) 장기, 기관" },
{ id: 1046, word: "organic", meaning: "유기농의" },
{ id: 1047, word: "origin", meaning: "원천, 근본, 출처" },
{ id: 1048, word: "originate", meaning: "일어나다, 생기다" },
{ id: 1049, word: "orphan", meaning: "고아로 만들다, 고아" },
{ id: 1050, word: "other than N", meaning: "N 외에" },
{ id: 1051, word: "own", meaning: "소유하다 (동사)" },
{ id: 1052, word: "participate (in N)", meaning: "(N에) 참가하다" },
{ id: 1053, word: "peak", meaning: "피크, 절정, 최고조" },
{ id: 1054, word: "peer", meaning: "1. 또래 2. 동료 3. 보다" },
{ id: 1055, word: "personal", meaning: "개인적인, 개인 맞춤형의" },
{ id: 1056, word: "personality", meaning: "성격" },
{ id: 1057, word: "philosophy", meaning: "철학" },
{ id: 1058, word: "photography", meaning: "촬영술" },
{ id: 1059, word: "pillow", meaning: "베개" },
{ id: 1060, word: "plenty of", meaning: "많은" },
{ id: 1061, word: "poetry", meaning: "시, 운문" },
{ id: 1062, word: "policy", meaning: "정책, 방침" },
{ id: 1063, word: "politely", meaning: "공손하게, 예의 바르게" },
{ id: 1064, word: "pollution", meaning: "오염" },
{ id: 1065, word: "possession", meaning: "소유물, 소유" },
{ id: 1066, word: "possibly", meaning: "아마도" },
{ id: 1067, word: "practical", meaning: "실질적인, 실용적인" },
{ id: 1068, word: "pray", meaning: "기도하다, 기도" },
{ id: 1069, word: "prescribe", meaning: "미리 확정하다, 처방하다" },
{ id: 1070, word: "price", meaning: "가격" },
{ id: 1071, word: "primary", meaning: "1차의" },
{ id: 1072, word: "primitive", meaning: "원시의, 원시시대의" },
{ id: 1073, word: "private", meaning: "사적인, 민간의 (사기업이 영리를 목적으로 운영하는)" },
{ id: 1074, word: "procedure", meaning: "절차" },
{ id: 1075, word: "profession", meaning: "직업" },
{ id: 1076, word: "promising", meaning: "유망한" },
{ id: 1077, word: "propose", meaning: "제안하다" },
{ id: 1078, word: "protest", meaning: "항의, 반대, 반대하다" },
{ id: 1079, word: "proverb", meaning: "속담" },
{ id: 1080, word: "pupil", meaning: "학생" },
{ id: 1081, word: "random", meaning: "무작위의, 임의의" },
{ id: 1082, word: "rapid", meaning: "신속한, 빠른" },
{ id: 1083, word: "rare", meaning: "드문, 희귀한" },
{ id: 1084, word: "rational", meaning: "이성적인, 합리적인" },
{ id: 1085, word: "raw", meaning: "날것의" },
{ id: 1086, word: "reaction", meaning: "반응" },
{ id: 1087, word: "reasonable", meaning: "합리적인" },
{ id: 1088, word: "recent", meaning: "최근의" },
{ id: 1089, word: "recipe", meaning: "조리법" },
{ id: 1090, word: "reflect on N", meaning: "N에 관하여 깊이 생각하다" },
{ id: 1091, word: "relation", meaning: "관계" },
{ id: 1092, word: "religion", meaning: "종교" },
{ id: 1093, word: "repair", meaning: "수리, 수리하다, 고치다" },
{ id: 1094, word: "repeatedly", meaning: "반복적으로" },
{ id: 1095, word: "replacement", meaning: "교체, 대체" },
{ id: 1096, word: "resemble", meaning: "닮다" },
{ id: 1097, word: "respondent", meaning: "응답자" },
{ id: 1098, word: "responsible", meaning: "책임 있는" },
{ id: 1099, word: "rest", meaning: "1. 나머지 2. 휴식" },
{ id: 1100, word: "restore", meaning: "회복하다, 재생하다" },
{ id: 1101, word: "retire", meaning: "은퇴하다" },
{ id: 1102, word: "ridiculous", meaning: "우스꽝스러운" },
{ id: 1103, word: "rise", meaning: "올라가다, 상승하다" },
{ id: 1104, word: "ritual", meaning: "의례적인 습관, 의례" },
{ id: 1105, word: "rub", meaning: "비비다, 문지르다" },
{ id: 1106, word: "ruin", meaning: "망치다" },
{ id: 1107, word: "run out of N", meaning: "N을 다 써버리다" },
{ id: 1108, word: "satisfactory", meaning: "만족스러운" },
{ id: 1109, word: "save", meaning: "저축하다, 절약하다" },
{ id: 1110, word: "scale", meaning: "1. 규모, 크기 2. 체중계 3. 비늘" },
{ id: 1111, word: "scan", meaning: "대충 훑어보다" },
{ id: 1112, word: "scary", meaning: "무서운" },
{ id: 1113, word: "secure", meaning: "단단히 지키다, 확실하게 하다" },
{ id: 1114, word: "security", meaning: "안전감, 안정감, 보안" },
{ id: 1115, word: "seed", meaning: "씨앗" },
{ id: 1116, word: "select", meaning: "(까다롭게) 선별하다" },
{ id: 1117, word: "self-esteem", meaning: "자존감" },
{ id: 1118, word: "servant", meaning: "신하, 하인" },
{ id: 1119, word: "sharp", meaning: "뾰족한, 예민한" },
{ id: 1120, word: "skip", meaning: "거르다" },
{ id: 1121, word: "society", meaning: "사회" },
{ id: 1122, word: "solely", meaning: "단독으로, 혼자" },
{ id: 1123, word: "sound", meaning: "1. 소리 2. (sound+형용사) ~하게 들리다" },
{ id: 1124, word: "spare", meaning: "면하게 하다, 막다" },
{ id: 1125, word: "specialist", meaning: "전문가" },
{ id: 1126, word: "speechless", meaning: "말을 못 하는, 할 말을 잃은" },
{ id: 1127, word: "spending", meaning: "지출" },
{ id: 1128, word: "stable", meaning: "안정적인" },
{ id: 1129, word: "standard", meaning: "표준, 기준" },
{ id: 1130, word: "stare", meaning: "응시하다" },
{ id: 1131, word: "steadily", meaning: "꾸준히, 착실하게, 견실하게" },
{ id: 1132, word: "steady", meaning: "꾸준한" },
{ id: 1133, word: "stem from", meaning: "~로부터 기인하다" },
{ id: 1134, word: "stream", meaning: "흐름, 이어지는 줄, 줄을 지어 이동하다" },
{ id: 1135, word: "striking", meaning: "두드러진" },
{ id: 1136, word: "study", meaning: "1. 공부, 공부하다 2. 연구" },
{ id: 1137, word: "submission", meaning: "제출" },
{ id: 1138, word: "subtle", meaning: "미묘한" },
{ id: 1139, word: "success", meaning: "성공" },
{ id: 1140, word: "successful", meaning: "성공적인" },
{ id: 1141, word: "successfully", meaning: "성공적으로" },
{ id: 1142, word: "sudden", meaning: "갑작스러운" },
{ id: 1143, word: "suddenly", meaning: "갑자기" },
{ id: 1144, word: "sufficient", meaning: "충분한" },
{ id: 1145, word: "surgery", meaning: "수술" },
{ id: 1146, word: "surround", meaning: "둘러싸다" },
{ id: 1147, word: "sustainable", meaning: "(친환경적으로) 지속 가능한" },
{ id: 1148, word: "tap", meaning: "가볍게 두드리기" },
{ id: 1149, word: "temperature", meaning: "기온" },
{ id: 1150, word: "temporary", meaning: "일시적인" },
{ id: 1151, word: "tension", meaning: "긴장" },
{ id: 1152, word: "the number of Ns", meaning: "N들의 수" },
{ id: 1153, word: "theme", meaning: "주제, 테마" },
{ id: 1154, word: "therapy", meaning: "치료, 요법" },
{ id: 1155, word: "though", meaning: "1. ~에도 불구하고 2. 하지만, 그러나" },
{ id: 1156, word: "thrive", meaning: "번창하다" },
{ id: 1157, word: "through N", meaning: "N을 통해서" },
{ id: 1158, word: "transportation", meaning: "운송" },
{ id: 1159, word: "trembling", meaning: "떨리는" },
{ id: 1160, word: "uncover", meaning: "알아내다" },
{ id: 1161, word: "underestimate", meaning: "과소평가하다" },
{ id: 1162, word: "undergo", meaning: "겪다" },
{ id: 1163, word: "unemployment", meaning: "실업" },
{ id: 1164, word: "universe", meaning: "우주" },
{ id: 1165, word: "useless", meaning: "쓸모없는, 소용없는" },
{ id: 1166, word: "valley", meaning: "계곡" },
{ id: 1167, word: "variable", meaning: "1. 변수 2. 바뀌는, 유동적인" },
{ id: 1168, word: "vehicle", meaning: "1. 차량 2. 수단" },
{ id: 1169, word: "viewpoint", meaning: "관점" },
{ id: 1170, word: "volume", meaning: "양, 부피" },
{ id: 1171, word: "weakness", meaning: "약점, 결점" },
{ id: 1172, word: "while SVO", meaning: "~하는 동안에, ~인 반면에" },
{ id: 1173, word: "whisper", meaning: "속삭이다, 귓속말" },
{ id: 1174, word: "worthwhile", meaning: "가치 있는" },
{ id: 1175, word: "wrinkle", meaning: "주름" },
{ id: 1176, word: "yet", meaning: "1. 하지만 2. 아직 ~않다" },
{ id: 1177, word: "aboard", meaning: "탑승한" },
{ id: 1178, word: "above all", meaning: "무엇보다도" },
{ id: 1179, word: "abundance", meaning: "풍족함" },
{ id: 1180, word: "accomplishment", meaning: "성과" },
{ id: 1181, word: "acknowledge", meaning: "인정하다, 승인하다" },
{ id: 1182, word: "across N", meaning: "1. N을 건너서 넘어서 2. N의 전반에" },
{ id: 1183, word: "action", meaning: "1. 행동 2. 조치" },
{ id: 1184, word: "adolescent", meaning: "청소년" },
{ id: 1185, word: "advanced", meaning: "진보적인, 앞선, 발전된" },
{ id: 1186, word: "after all", meaning: "결국" },
{ id: 1187, word: "afterward", meaning: "후에, 나중에" },
{ id: 1188, word: "against N", meaning: "N에 대항하여, 맞서서, 반대하여" },
{ id: 1189, word: "aggressive", meaning: "공격적인" },
{ id: 1190, word: "agree", meaning: "의견이 일치하다, 동의하다" },
{ id: 1191, word: "agreement", meaning: "의견 일치, 동의" },
{ id: 1192, word: "airline", meaning: "항공사" },
{ id: 1193, word: "all of a sudden", meaning: "갑자기" },
{ id: 1194, word: "alongside N", meaning: "N을 따라서, N 옆에서" },
{ id: 1195, word: "amateur", meaning: "아마추어, 비전문가" },
{ id: 1196, word: "amusement park", meaning: "놀이공원" },
{ id: 1197, word: "anticipation", meaning: "기대" },
{ id: 1198, word: "appeal", meaning: "호소하다" },
{ id: 1199, word: "appliance", meaning: "(가정용) 기기" },
{ id: 1200, word: "application", meaning: "지원, 신청" },
{ id: 1201, word: "appoint", meaning: "임명하다" },
{ id: 1202, word: "approve", meaning: "찬성하다, 승인하다" },
{ id: 1203, word: "approximately", meaning: "대략" },
{ id: 1204, word: "architecture", meaning: "건축" },
{ id: 1205, word: "area", meaning: "1. 지역 2. 분야" },
{ id: 1206, word: "arouse", meaning: "1. 불러일으키다 2. 각성시키다" },
{ id: 1207, word: "arrival", meaning: "도착" },
{ id: 1208, word: "art", meaning: "1. 예술 2. 기술" },
{ id: 1209, word: "artificial", meaning: "인공적인" },
{ id: 1210, word: "as if SVO", meaning: "마치 ~인 것처럼" },
{ id: 1211, word: "as though SVO", meaning: "마치 ~인 것처럼" },
{ id: 1212, word: "associate A with B", meaning: "A를 B와 관련짓다" },
{ id: 1213, word: "association", meaning: "1. 연관성 2. 협회" },
{ id: 1214, word: "assure", meaning: "안심시키다" },
{ id: 1215, word: "attachment", meaning: "1. 애착 2. 첨부" },
{ id: 1216, word: "automatic", meaning: "1. 자동적인 2. 무의식적인" },
{ id: 1217, word: "automobile", meaning: "자동차" },
{ id: 1218, word: "awaken", meaning: "(잠에서) 깨다, 깨우다" },
{ id: 1219, word: "band", meaning: "악단, 무리" },
{ id: 1220, word: "bathe", meaning: "(빛, 온기 따위로) 감싸다" },
{ id: 1221, word: "faced (with N)", meaning: "(N에) 직면한" },
{ id: 1222, word: "be made up of N", meaning: "N으로 구성되다" },
{ id: 1223, word: "beam", meaning: "빛줄기, 빔" },
{ id: 1224, word: "beast", meaning: "짐승" },
{ id: 1225, word: "beg", meaning: "부탁하다" },
{ id: 1226, word: "beggar", meaning: "걸인, 거지" },
{ id: 1227, word: "belong (to N)", meaning: "(N에) 속하다" },
{ id: 1228, word: "bet", meaning: "단언하다, 내기하다" },
{ id: 1229, word: "bin", meaning: "쓰레기통" },
{ id: 1230, word: "blood", meaning: "피" },
{ id: 1231, word: "blow", meaning: "불다, 날려 보내다, 강타" },
{ id: 1232, word: "book", meaning: "1. 예약하다 2. 책" },
{ id: 1233, word: "border", meaning: "국경" },
{ id: 1234, word: "bottom", meaning: "아래(의)" },
{ id: 1235, word: "bowl", meaning: "그릇, 사발" },
{ id: 1236, word: "break", meaning: "1. 깨다 2. 휴식, 방학" },
{ id: 1237, word: "brief", meaning: "간결한, 짧은" },
{ id: 1238, word: "broad", meaning: "넓은" },
{ id: 1239, word: "browse", meaning: "훑어보다" },
{ id: 1240, word: "bucket", meaning: "통, 양동이" },
{ id: 1241, word: "bush", meaning: "덤불" },
{ id: 1242, word: "by contrast", meaning: "이와 대조적으로" },
{ id: 1243, word: "by Ving", meaning: "~함으로써" },
{ id: 1244, word: "cage", meaning: "(동물을 가두는) 우리" },
{ id: 1245, word: "calculus", meaning: "미적분학" },
{ id: 1246, word: "capability", meaning: "능력" },
{ id: 1247, word: "captain", meaning: "(해군) 대령, 대장" },
{ id: 1248, word: "careful", meaning: "주의하는, 조심하는, 사려 깊은" },
{ id: 1249, word: "causal", meaning: "인과관계의" },
{ id: 1250, word: "ceremony", meaning: "식, 의식, 제전" },
{ id: 1251, word: "challenging", meaning: "어려운, 힘든, 도전적인" },
{ id: 1252, word: "chances are that SVO", meaning: "아마 ~일 가능성이 있다" },
{ id: 1253, word: "cheer", meaning: "응원하다" },
{ id: 1254, word: "chief", meaning: "추장, 장, 대표" },
{ id: 1255, word: "chore", meaning: "집안일, 허드렛일" },
{ id: 1256, word: "cite", meaning: "인용하다, 언급하다" },
{ id: 1257, word: "citizen", meaning: "시민" },
{ id: 1258, word: "closely", meaning: "밀접하게" },
{ id: 1259, word: "college", meaning: "대학" },
{ id: 1260, word: "combat", meaning: "전투" },
{ id: 1261, word: "commitment", meaning: "1. 헌신 2. 약속" },
{ id: 1262, word: "common", meaning: "흔한, 공통된" }
    // ... 실제 사용 시에는 여기에 단어를 더 추가해서 50개를 만드세요.
];

// '소연이 단어장' 데이터 (요구사항에 맞게 단어를 추가/수정하세요)
const wordDatabaseSoyeon = [
  { id: 1, word: "A and B alike", meaning: "A와 B 둘 다" },
  { id: 2, word: "A as well as B", meaning: "B뿐만 아니라 A도" },
  { id: 3, word: "a bit / a bit of N", meaning: "약간, 조금 / 약간의 N" },
  { id: 4, word: "a degree of N", meaning: "어느 정도의 N" },
  { id: 5, word: "a great deal of", meaning: "다량의, 많은" },
  { id: 6, word: "A have (a lot) to do with B", meaning: "A는 B와 관련이 (많이) 있다" },
  { id: 7, word: "A have nothing to do with B", meaning: "A는 B와 관련이 전혀 없다" },
  { id: 8, word: "a must", meaning: "필수품, 의무" },
  { id: 9, word: "a number of Ns", meaning: "많은 N들" },
  { id: 10, word: "A outnumber B", meaning: "A는 B보다 수가 많다" },
  { id: 11, word: "a range of Ns", meaning: "다양한 N들" },
  { id: 12, word: "a spirit of community", meaning: "공동체 의식" },
  { id: 13, word: "a third", meaning: "3분의 1" },
  { id: 14, word: "a variety of Ns", meaning: "다양한 N들" },
  { id: 15, word: "abandon", meaning: "버리다" },
  { id: 16, word: "ability", meaning: "능력" },
  { id: 17, word: "abnormal", meaning: "비정상적인" },
  { id: 18, word: "aboard", meaning: "탑승한" },
  { id: 19, word: "above all", meaning: "무엇보다도" },
  { id: 20, word: "above N", meaning: "N 위에" },
  { id: 21, word: "abroad", meaning: "외국에" },
  { id: 22, word: "absence", meaning: "부재" },
  { id: 23, word: "absent", meaning: "아무 생각 없는, 멍한" },
  { id: 24, word: "absolute", meaning: "절대적인 (변하지 않는, 세상 하나라는 의미)" },
  { id: 25, word: "absorb", meaning: "흡수하다" },
  { id: 26, word: "absorption", meaning: "흡수" },
  { id: 27, word: "abstract", meaning: "추상적인" },
  { id: 28, word: "abundance", meaning: "풍족함" },
  { id: 29, word: "abundant", meaning: "풍부한" },
  { id: 30, word: "abuse", meaning: "남용, 학대; 남용[오용]하다, 학대하다" },
  { id: 31, word: "academic", meaning: "학업의" },
  { id: 32, word: "academic performance", meaning: "학업 성적" },
  { id: 33, word: "academy", meaning: "학문기관 (학원, 학교 등)" },
  { id: 34, word: "accelerated", meaning: "가속화된, 앞당겨진" },
  { id: 35, word: "acceleration", meaning: "가속화" },
  { id: 36, word: "accent", meaning: "1. 강세, 억양 2. 사투리 3. 강조하다" },
  { id: 37, word: "accept", meaning: "받아들이다, 수락하다" },
  { id: 38, word: "acceptable", meaning: "받아들여질 수 있는" },
  { id: 39, word: "acceptance", meaning: "수용, 받아들임" },
  { id: 40, word: "access", meaning: "접근" },
  { id: 41, word: "accessibility", meaning: "접근성" },
  { id: 42, word: "accessible", meaning: "접근하기 쉬운" },
  { id: 43, word: "accident", meaning: "사고, 우연" },
  { id: 44, word: "accidentally", meaning: "우연히" },
  { id: 45, word: "acclaimed", meaning: "칭송받는" },
  { id: 46, word: "accommodate", meaning: "수용하다" },
  { id: 47, word: "accommodation", meaning: "숙박" },
  { id: 48, word: "accompany", meaning: "동반하다, 동행하다" },
  { id: 49, word: "accomplish", meaning: "성취하다" },
  { id: 50, word: "accomplish / achieve", meaning: "성취하다" },
  { id: 51, word: "accomplished", meaning: "성공한" },
  { id: 52, word: "accomplishment", meaning: "성과" },
  { id: 53, word: "accord", meaning: "v. 일치하다, 부여하다 n. 일치, 합의" },
  { id: 54, word: "according to", meaning: "~에 따르면" },
  { id: 55, word: "accordingly", meaning: "따라서" },
  { id: 56, word: "account", meaning: "1. 설명 2. 계좌" },
  { id: 57, word: "account for N", meaning: "1. (비율을) 차지하다 2. 설명하다" },
  { id: 58, word: "accountant", meaning: "회계사" },
  { id: 59, word: "accumulate", meaning: "축적하다" },
  { id: 60, word: "accumulation", meaning: "축적" },
  { id: 61, word: "accuracy", meaning: "정확성" },
  { id: 62, word: "accurate", meaning: "정확한" },
  { id: 63, word: "accurately", meaning: "정확하게" },
  { id: 64, word: "accusation", meaning: "비난; 고발, 기소" },
  { id: 65, word: "ache", meaning: "아프다" },
  { id: 66, word: "achieve", meaning: "성취하다" },
  { id: 67, word: "achievement", meaning: "성취" },
  { id: 68, word: "acid", meaning: "산성의, 신맛이 나는 / 산" },
  { id: 69, word: "acknowledge", meaning: "인정하다, 승인하다" },
  { id: 70, word: "acne", meaning: "여드름" },
  { id: 71, word: "acoustic", meaning: "소리의, 음향의 / 청각의" },
  { id: 72, word: "acquire", meaning: "얻다, 습득하다" },
  { id: 73, word: "acquisition", meaning: "습득" },
  { id: 74, word: "across N", meaning: "1. N을 건너서, 넘어서 2. N의 전반에" },
  { id: 75, word: "act", meaning: "1. 행동하다 2. 연기하다 3. 작용하다" },
  { id: 76, word: "action", meaning: "1. 행동 2. 조치" },
  { id: 77, word: "activate", meaning: "활성화시키다" },
  { id: 78, word: "active", meaning: "적극적인, 활동중인" },
  { id: 79, word: "activist", meaning: "활동가" },
  { id: 80, word: "activity", meaning: "활동" },
  { id: 81, word: "actor", meaning: "배우" },
  { id: 82, word: "actual", meaning: "실제의, 사실상의" },
  { id: 83, word: "actually", meaning: "실제로" },
  { id: 84, word: "ad", meaning: "광고" },
  { id: 85, word: "adapt", meaning: "적응하다, 맞추다" },
  { id: 86, word: "adaptation", meaning: "조정, 적응" },
  { id: 87, word: "add", meaning: "더하다, 추가하다" },
  { id: 88, word: "addict", meaning: "중독시키다, 중독자" },
  { id: 89, word: "addiction", meaning: "중독" },
  { id: 90, word: "additional", meaning: "추가적인, 부수적인" },
  { id: 91, word: "additionally", meaning: "게다가, 또한, 더군다나" },
  { id: 92, word: "address", meaning: "1. 주소 2. 연설하다, 말하다 3. 다루다" },
  { id: 93, word: "adequate", meaning: "적절한" },
  { id: 94, word: "adequately", meaning: "적절하게" },
  { id: 95, word: "adjust", meaning: "조정하다, 조절하다" },
  { id: 96, word: "adjustment", meaning: "조정" },
  { id: 97, word: "admire", meaning: "칭찬하다, 감탄하다" },
  { id: 98, word: "admission", meaning: "1. 인정, 시인 2. 허가 3. 입장료" },
  { id: 99, word: "admit", meaning: "1. (잘못, 사실 등) 인정하다 2. 허락하다" },
  { id: 100, word: "adolescent", meaning: "청소년" },
  { id: 101, word: "adopt", meaning: "1. 채택하다 2. 입양하다" },
  { id: 102, word: "adorable", meaning: "사랑스러운" },
  { id: 103, word: "adult", meaning: "성인" },
  { id: 104, word: "adulthood", meaning: "성인기" },
  { id: 105, word: "advance", meaning: "진보, 발전 / 나아가다" },
  { id: 106, word: "advance notice", meaning: "사전 통보" },
  { id: 107, word: "advanced", meaning: "진보적인, 앞선, 발전된" },
  { id: 108, word: "advancement", meaning: "발전, 진보" },
  { id: 109, word: "advantage", meaning: "이익" },
  { id: 110, word: "advantageous", meaning: "이로운, 유리한" },
  { id: 111, word: "adventurous", meaning: "모험적인, 위험이 많은" },
  { id: 112, word: "adverb", meaning: "부사" },
  { id: 113, word: "adversary", meaning: "상대, 적수" },
  { id: 114, word: "advertise", meaning: "광고하다" },
  { id: 115, word: "advertisement", meaning: "광고" },
  { id: 116, word: "advice / advise", meaning: "조언 / 조언하다" },
  { id: 117, word: "advisor", meaning: "조언자" },
  { id: 118, word: "advocate", meaning: "1. 옹호하다 2. 옹호자, 변호사" },
  { id: 119, word: "aerobic", meaning: "유산소의" },
  { id: 120, word: "aeroplane", meaning: "비행기" },
  { id: 121, word: "affair", meaning: "문제, 일, 행사" },
  { id: 122, word: "affect N", meaning: "N에게 영향을 주다" },
  { id: 123, word: "affective", meaning: "정서적인" },
  { id: 124, word: "afford to V", meaning: "~할 여유가 있다" },
  { id: 125, word: "affordable", meaning: "(금전적, 시간적) 여유가 되는" },
  { id: 126, word: "after a while", meaning: "잠시 후" },
  { id: 127, word: "after all", meaning: "결국" },
  { id: 128, word: "afterward", meaning: "후에, 나중에" },
  { id: 129, word: "against N", meaning: "N에 대항하여, 맞서서, 반대하여" },
  { id: 130, word: "age group", meaning: "연령 집단" },
  { id: 131, word: "agency, agent", meaning: "기관, 단체 / 대리인, 행위자" },
  { id: 132, word: "aggression", meaning: "공격성" },
  { id: 133, word: "aggressive", meaning: "공격적인" },
  { id: 134, word: "aggressively", meaning: "공격적으로" },
  { id: 135, word: "aging", meaning: "노화" },
  { id: 136, word: "agree", meaning: "의견이 일치하다, 동의하다" },
  { id: 137, word: "agreement", meaning: "의견일치, 동의" },
  { id: 138, word: "agricultural", meaning: "농업의" },
  { id: 139, word: "agriculture", meaning: "농업" },
  { id: 140, word: "ahead", meaning: "미리" },
  { id: 141, word: "ahead of N", meaning: "N 앞에" },
  { id: 142, word: "aid", meaning: "1. 돕다 2. 도움" },
  { id: 143, word: "aim", meaning: "1. 목표 2. 목표로 하다" },
  { id: 144, word: "air", meaning: "1. 공기 2. 방송되다" },
  { id: 145, word: "air conditioner", meaning: "에어컨" },
  { id: 146, word: "aircraft", meaning: "항공기" },
  { id: 147, word: "aircraft carrier", meaning: "항공모함" },
  { id: 148, word: "airline", meaning: "항공사" },
  { id: 149, word: "air-tight", meaning: "밀폐된" },
  { id: 150, word: "alarm", meaning: "1. 놀라게 하다 2. 자명종, 경고신호" },
  { id: 151, word: "alarm call", meaning: "경고 신호, 경계 호출" },
{ id: 152, word: "alarm signal", meaning: "(위험에 대해 미리 알리는) 경고 신호" },
{ id: 153, word: "alchemist", meaning: "연금술사 (무에서 유를 창조하고자 흙을 금으로 바꾸는 걸 연구하던 사람)" },
{ id: 154, word: "alchemy", meaning: "연금술" },
{ id: 155, word: "alert", meaning: "1. 기민한, 정신을 바짝 차린, 각성한, 경계하는 2. 알리다" },
{ id: 156, word: "alertness", meaning: "각성, 빈틈없음" },
{ id: 157, word: "alien", meaning: "외국인, 외계인, 외국(인)의, 외계의, 외국의" },
{ id: 158, word: "alike", meaning: "비슷한" },
{ id: 159, word: "alive", meaning: "살아있는" },
{ id: 160, word: "all of a sudden", meaning: "갑자기" },
{ id: 161, word: "allergy", meaning: "알레르기" },
{ id: 162, word: "alligator", meaning: "악어" },
{ id: 163, word: "allocate", meaning: "할당하다" },
{ id: 164, word: "allot", meaning: "할당하다" },
{ id: 165, word: "allow", meaning: "허락하다" },
{ id: 166, word: "allowance", meaning: "용돈" },
{ id: 167, word: "almost", meaning: "거의" },
{ id: 168, word: "alone", meaning: "홀로, 외로이" },
{ id: 169, word: "along N", meaning: "N을 따라서" },
{ id: 170, word: "along with N", meaning: "N과 더불어 함께" },
{ id: 171, word: "alongside N", meaning: "N을 따라서, N 옆에서" },
{ id: 172, word: "aloud", meaning: "큰 소리로" },
{ id: 173, word: "already", meaning: "이미" },
{ id: 174, word: "also", meaning: "또한" },
{ id: 175, word: "alter", meaning: "바꾸다" },
{ id: 176, word: "alternate", meaning: "번갈아 교대하는 / 번갈아 교대하다" },
{ id: 177, word: "alternately", meaning: "교대로, 번갈아서" },
{ id: 178, word: "alternative", meaning: "대안적인 / 대안" },
{ id: 179, word: "alternatively", meaning: "대안으로" },
{ id: 180, word: "although SVO", meaning: "비록 ~일지라도" },
{ id: 181, word: "altitude", meaning: "고도" },
{ id: 182, word: "altogether", meaning: "모두, 함께" },
{ id: 183, word: "amateur", meaning: "아마추어, 비전문가" },
{ id: 184, word: "amaze", meaning: "놀라게 하다, 경악하게 하다" },
{ id: 185, word: "amenities", meaning: "편의 서비스" },
{ id: 186, word: "among N", meaning: "N 사이에서" },
{ id: 187, word: "amount (명사)", meaning: "양, 금액, 총액" },
{ id: 188, word: "amount to N (동사)", meaning: "(합계가) ~에 이르다, 달하다" },
{ id: 189, word: "amuse", meaning: "재미나게 하다" },
{ id: 190, word: "amusement", meaning: "즐거움, 재미, 놀이, 오락" },
{ id: 191, word: "amusement park", meaning: "놀이공원" },
{ id: 192, word: "analogy", meaning: "1. 유추, 비유 2. 유사성" },
{ id: 193, word: "analysis", meaning: "분석" },
{ id: 194, word: "analyst", meaning: "분석가" },
{ id: 195, word: "analytical", meaning: "분석적인" },
{ id: 196, word: "analyze", meaning: "분석하다" },
{ id: 197, word: "ancestor", meaning: "조상" },
{ id: 198, word: "ancestral", meaning: "선조의" },
{ id: 199, word: "anchor", meaning: "1. 닻 2. 고정하다 3. 방송앵커(사회자)" },
{ id: 200, word: "ancient", meaning: "고대의" },
{ id: 201, word: "and so forth = and so on", meaning: "기타 등등" },
{ id: 202, word: "and yet", meaning: "그러나" },
{ id: 203, word: "anecdote", meaning: "일화" },
{ id: 204, word: "angel", meaning: "천사" },
{ id: 205, word: "anger", meaning: "분노" },
{ id: 206, word: "angle", meaning: "각도" },
{ id: 207, word: "animated", meaning: "만화영화의" },
{ id: 208, word: "ankle", meaning: "발목, 복사뼈" },
{ id: 209, word: "anniversary", meaning: "기념일" },
{ id: 210, word: "announce", meaning: "발표하다" },
{ id: 211, word: "announcement", meaning: "발표, 공표" },
{ id: 212, word: "annoy", meaning: "화나게 하다" },
{ id: 213, word: "annual", meaning: "매년의, 연례의" },
{ id: 214, word: "Antarctic", meaning: "남극의" },
{ id: 215, word: "anthropologist", meaning: "인류학자" },
{ id: 216, word: "antibacterial", meaning: "항 박테리아" },
{ id: 217, word: "antibiotic", meaning: "항생제" },
{ id: 218, word: "anticipate", meaning: "기대하다, 예감하다" },
{ id: 219, word: "anticipation", meaning: "기대" },
{ id: 220, word: "anxiety", meaning: "불안감" },
{ id: 221, word: "anxious", meaning: "불안해하는, 염려하는" },
{ id: 222, word: "anyway", meaning: "어쨌든, 여하튼" },
{ id: 223, word: "apart", meaning: "떨어진 / 떨어져서" },
{ id: 224, word: "apartment", meaning: "아파트, (휴양지) 콘도" },
{ id: 225, word: "apartment complex", meaning: "아파트 단지" },
{ id: 226, word: "ape", meaning: "유인원, 영장류" },
{ id: 227, word: "apologize", meaning: "사과하다" },
{ id: 228, word: "apology", meaning: "사과" },
{ id: 229, word: "apparent", meaning: "명백한" },
{ id: 230, word: "apparently", meaning: "명백하게" },
{ id: 231, word: "appeal", meaning: "호소하다" },
{ id: 232, word: "appealing", meaning: "매력적인, 흥미를 끄는" },
{ id: 233, word: "appear", meaning: "1. 나타나다 2. appear to V : toV 하는듯 보이다" },
{ id: 234, word: "appearance", meaning: "1. 외모, 외양 2. 등장" },
{ id: 235, word: "appetizer", meaning: "식욕을 돋우기 위한 것" },
{ id: 236, word: "applaud", meaning: "박수를 치다" },
{ id: 237, word: "applause", meaning: "박수갈채" },
{ id: 238, word: "appliance", meaning: "(가정용) 기기" },
{ id: 239, word: "applicable", meaning: "적용되는" },
{ id: 240, word: "applicant", meaning: "지원자" },
{ id: 241, word: "application", meaning: "지원, 신청" },
{ id: 242, word: "application form", meaning: "지원서" },
{ id: 243, word: "apply", meaning: "1. (for) 신청하다, 지원하다 2. (to) ~에 적용되다" },
{ id: 244, word: "appoint", meaning: "임명하다" },
{ id: 245, word: "appointment", meaning: "약속" },
{ id: 246, word: "appreciate", meaning: "1. 감사하다 2. 감상하다 3. 인정하다 4. 인식하다" },
{ id: 247, word: "appreciation", meaning: "1. 감사 2. 감상 3. 인정 4. 인식" },
{ id: 248, word: "approach", meaning: "접근하다, 다가가다 / 접근, 접근법" },
{ id: 249, word: "appropriate", meaning: "적절한" },
{ id: 250, word: "approval", meaning: "인정, 승인, 허가" },
{ id: 251, word: "approve", meaning: "찬성하다, 승인하다" },
{ id: 252, word: "approximately", meaning: "대략" },
{ id: 253, word: "apron", meaning: "앞치마" },
{ id: 254, word: "arch", meaning: "아치, 아치 모양 / 구부리다" },
{ id: 255, word: "architect", meaning: "건축가" },
{ id: 256, word: "architecture", meaning: "건축" },
{ id: 257, word: "archiving", meaning: "(체계적인) 파일 보관" },
{ id: 258, word: "area", meaning: "1. 지역 2. 분야" },
{ id: 259, word: "arena", meaning: "경기장" },
{ id: 260, word: "argue", meaning: "주장하다" },
{ id: 261, word: "argument", meaning: "1. 주장 2. 말다툼, 논쟁" },
{ id: 262, word: "arise-arouse-arisen", meaning: "일어나다, 발생하다" },
{ id: 263, word: "arm", meaning: "1. 팔 2. 무기 3. 무장하다" },
{ id: 264, word: "armed", meaning: "(무기로) 무장한" },
{ id: 265, word: "armor", meaning: "갑옷" },
{ id: 266, word: "army", meaning: "군대" },
{ id: 267, word: "around N", meaning: "1. N의 주변에 2. 대략 N" },
{ id: 268, word: "around the world", meaning: "전 세계, 세계 곳곳에, 세계 일주의" },
{ id: 269, word: "arouse", meaning: "1. 불러일으키다 2. 각성시키다" },
{ id: 270, word: "arrange", meaning: "배열하다, 정렬하다" },
{ id: 271, word: "arrangement", meaning: "배열, 정렬" },
{ id: 272, word: "arrest", meaning: "체포하다" },
{ id: 273, word: "arrival", meaning: "도착" },
{ id: 274, word: "arrogant", meaning: "거만한" },
{ id: 275, word: "arrow", meaning: "화살" },
{ id: 276, word: "art", meaning: "1. 예술 2. 기술" },
{ id: 277, word: "article", meaning: "1. 신문기사 2. 물건 3. (문법) 관사" },
{ id: 278, word: "artifact", meaning: "유물, 공예품" },
{ id: 279, word: "artificial", meaning: "인공적인" },
{ id: 280, word: "artificial intelligence", meaning: "(AI) 인공지능" },
{ id: 281, word: "artistic", meaning: "예술적인" },
{ id: 282, word: "artwork", meaning: "미술품, 예술품" },
{ id: 283, word: "as if SVO", meaning: "마치 ~인 것 처럼" },
{ id: 284, word: "as it is", meaning: "있는 그대로" },
{ id: 285, word: "as long as SVO", meaning: "~하는 한" },
{ id: 286, word: "as opposed to N", meaning: "N에 반대하여" },
{ id: 287, word: "as soon as SVO", meaning: "~하자마자" },
{ id: 288, word: "as though SVO", meaning: "마치 ~인 것 처럼" },
{ id: 289, word: "as usual", meaning: "늘 그렇듯, 평상시처럼" },
{ id: 290, word: "as well", meaning: "또한" },
{ id: 291, word: "ash", meaning: "재" },
{ id: 292, word: "ashamed", meaning: "부끄러워하는" },
{ id: 293, word: "ask for", meaning: "요청하다" },
{ id: 294, word: "asleep", meaning: "잠든" },
{ id: 295, word: "aspect", meaning: "국면, 양상, 측면" },
{ id: 296, word: "aspiration", meaning: "열망" },
{ id: 297, word: "aspire", meaning: "열망하다" },
{ id: 298, word: "assemble", meaning: "모으다, 조립하다" },
{ id: 299, word: "assembly", meaning: "조립" },
{ id: 300, word: "assert", meaning: "주장하다" }
];

const wordbooks = { jiseong: wordDatabaseJiseong, soyeon: wordDatabaseSoyeon };

// 게임 상태 변수
let wordDatabase; // 현재 선택된 단어장
let currentList = [];
let wrongAnswers = [];
let currentIndex = 0;
let score = 0;
let isReviewMode = false;
let startTime = 0; // 게임 시작 시간 기록

// DOM 요소
const startScreen = document.getElementById('start-screen');
const gameScreen = document.getElementById('game-screen');
const endScreen = document.getElementById('end-screen');
const wordDisplay = document.getElementById('english-word');
const inputField = document.getElementById('user-input');
const feedbackIcon = document.getElementById('feedback-icon');
const progressText = document.getElementById('progress-text');
const scoreText = document.getElementById('score-text');
const totalWordsSpan = document.getElementById('total-words');
const wordRangeInfo = document.getElementById('word-range-info');

// 초기화 함수: 페이지 로드 시 실행
document.addEventListener('DOMContentLoaded', () => {
    // HTML에 단어장 선택 라디오 버튼이 있다고 가정하고 이벤트 리스너를 추가합니다.
    document.querySelectorAll('input[name="wordbook"]').forEach(radio => {
        radio.addEventListener('change', (e) => switchWordbook(e.target.value));
    });

    // 기본값으로 '지성이 단어장'을 선택하고 정보를 표시합니다.
    switchWordbook('jiseong');
    // 라디오 버튼의 초기 선택 상태도 동기화합니다.
    const defaultRadio = document.querySelector('input[name="wordbook"][value="jiseong"]');
    if (defaultRadio) defaultRadio.checked = true;
});

// 단어장 전환 및 정보 업데이트 함수
function switchWordbook(bookName) {
    wordDatabase = wordbooks[bookName];

    if (!wordDatabase || wordDatabase.length === 0) {
        totalWordsSpan.innerText = '0';
        if (wordRangeInfo) wordRangeInfo.innerText = '(단어 없음)';
        return;
    }

    totalWordsSpan.innerText = wordDatabase.length;
    const minId = wordDatabase[0].id;
    const maxId = wordDatabase[wordDatabase.length - 1].id;
    if (wordRangeInfo) wordRangeInfo.innerText = `(단어 ID 범위: ${minId} ~ ${maxId})`;
}

// 게임 시작
function startGame() {
    const startInput = document.getElementById('start-range').value;
    const endInput = document.getElementById('end-range').value;
    const order = document.querySelector('input[name="order"]:checked')?.value || 'random'; // 순서 선택 확인
    let targetList = [];

    // 범위 입력 확인
    if (startInput && endInput) {
        const start = parseInt(startInput);
        const end = parseInt(endInput);

        if (start > end || start < 1) {
            alert("올바른 범위를 입력해주세요.");
            return;
        }
        
        // 해당 범위의 단어만 필터링 (id 기준)
        targetList = wordDatabase.filter(item => item.id >= start && item.id <= end);
        
        if (targetList.length === 0) {
            alert("해당 범위에 단어가 없습니다.");
            return;
        }
    } else {
        // 범위 입력이 없으면 전체에서 랜덤 50개
        targetList = [...wordDatabase].sort(() => Math.random() - 0.5).slice(0, 50);
    }

    // 선택된 리스트를 섞어서 게임 시작
    currentList = targetList.sort(() => Math.random() - 0.5);
    if (order === 'random') {
        currentList = targetList.sort(() => Math.random() - 0.5);
    } else {
        // 번호순 정렬 (id 기준 오름차순)
        currentList = targetList.sort((a, b) => a.id - b.id);
    }

    wrongAnswers = [];
    currentIndex = 0;
    score = 0;
    isReviewMode = false;
    startTime = Date.now(); // 시작 시간 기록
    
    showScreen('game-screen');
    loadWord();
}

// 화면 전환
function showScreen(screenId) {
    document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
    document.getElementById(screenId).classList.add('active');
}

// 단어 불러오기
function loadWord() {
    const currentWord = currentList[currentIndex];
    wordDisplay.innerText = currentWord.word;
    inputField.value = '';
    inputField.focus();
    
    // UI 초기화
    feedbackIcon.innerText = '😐'; // 기본 표정
    feedbackIcon.classList.remove('bounce', 'shake');
    
    // 진행 상황 업데이트
    const total = currentList.length;
    progressText.innerText = `문제: ${currentIndex + 1} / ${total}`;
    scoreText.innerText = `점수: ${score}`;
}

// 정답 확인
function checkAnswer() {
    const userAnswer = inputField.value.trim();
    const currentWord = currentList[currentIndex];

    if (!userAnswer) return; // 빈 입력 방지

    // 쉼표(,)로 구분된 뜻 중 하나라도 맞으면 정답 처리
    // 예: "대우, 취급, 치료" -> ["대우", "취급", "치료"]
    // 띄어쓰기 무시를 위해 정답과 입력값 모두 공백 제거
    const userAnswerClean = userAnswer.replace(/\s+/g, '');
    const correctMeaningsClean = currentWord.meaning.split(',').map(m => m.trim().replace(/\s+/g, ''));

    if (correctMeaningsClean.includes(userAnswerClean)) {
        // 정답: 칭찬 + 행복한 표정
        feedbackIcon.innerText = '😍';
        feedbackIcon.classList.add('bounce');
        score++;
        setTimeout(nextWord, 1000); // 1초 뒤 다음 문제
    } else {
        // 오답: 놀리는 표정
        feedbackIcon.innerText = '😜';
        feedbackIcon.classList.add('shake');
        
        // 정답(뜻)을 화면에 잠깐 보여줌
        wordDisplay.innerText = currentWord.meaning;

        // 중복 방지하며 오답 노트에 추가
        if (!wrongAnswers.includes(currentWord)) {
            wrongAnswers.push(currentWord);
        }
        setTimeout(nextWord, 1000); // 1초 뒤 다음 문제
    }
}

// 다음 문제로 이동
function nextWord() {
    currentIndex++;
    if (currentIndex < currentList.length) {
        loadWord();
    } else {
        endGame();
    }
}

// 게임 종료
function endGame() {
    showScreen('end-screen');
    
    // 총 걸린 시간 계산 및 표시
    const endTime = Date.now();
    const timeTaken = ((endTime - startTime) / 1000).toFixed(1); // 초 단위, 소수점 1자리
    alert(`수고하셨습니다! 총 걸린 시간: ${timeTaken}초`);

    const resultMsg = document.getElementById('result-message');
    const reviewBtn = document.getElementById('review-btn');
    const wrongAnswerContainer = document.getElementById('wrong-answer-container');
    const tableBody = document.getElementById('wrong-answer-table-body');
    
    resultMsg.innerText = `총 ${currentList.length}문제 중 ${score}개를 맞췄어요!`;
    
    if (wrongAnswers.length > 0) {
        reviewBtn.classList.remove('hidden');
        reviewBtn.innerText = `틀린 ${wrongAnswers.length}문제 다시 풀기`;

        // 틀린 단어 테이블 표시
        if (wrongAnswerContainer && tableBody) {
            wrongAnswerContainer.classList.remove('hidden');
            tableBody.innerHTML = '';
            wrongAnswers.forEach(item => {
                const row = document.createElement('tr');
                row.innerHTML = `<td style="padding: 8px; border-bottom: 1px solid #eee;">${item.word}</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${item.meaning}</td>`;
                tableBody.appendChild(row);
            });
        }
    } else {
        reviewBtn.classList.add('hidden');
        if (wrongAnswerContainer) wrongAnswerContainer.classList.add('hidden');
        resultMsg.innerText += "\n완벽해요! 모든 문제를 맞췄습니다! 🏆";
    }
}

// 틀린 문제 다시 풀기 (오답 노트)
function startReview() {
    currentList = [...wrongAnswers]; // 틀린 문제만 복사
    wrongAnswers = []; // 오답 초기화 (다시 틀리면 또 쌓임)
    currentIndex = 0;
    score = 0;
    isReviewMode = true;
    startTime = Date.now(); // 리뷰 모드 시작 시간도 기록
    
    showScreen('game-screen');
    loadWord();
}

// 처음부터 다시하기
function restartGame() {
    startGame();
}

// 음성 인식 (마이크 입력)
function startVoiceInput() {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    
    if (!SpeechRecognition) {
        alert("이 브라우저는 음성 인식을 지원하지 않습니다. 크롬 브라우저를 사용해보세요.");
        return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = 'ko-KR'; // 한국어 인식
    recognition.start();

    recognition.onresult = function(event) {
        const transcript = event.results[0][0].transcript.replace(/\.$/, '');
        inputField.value = transcript; // 인식된 텍스트를 입력창에 넣음
        checkAnswer(); // 자동으로 정답 확인
    };
}

// 엔터키 입력 지원
inputField.addEventListener('keypress', function (e) {
    if (e.key === 'Enter') {
        checkAnswer();
    }
});
